// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdmvswncohbtlcenmxhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkbXZzd25jb2hidGxjZW5teGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDgxNzksImV4cCI6MjA1OTAyNDE3OX0.vId04CzzsLWRT4y4vxf9ioQSsG-oHmyl4doXF80Stg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);